name: OSS Safety Check with RL-Protect

on:
  workflow_dispatch:

jobs:

  OSS-Check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out 
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: 3.14
          check-latest: true
          pip-install: rl-protect

      - name: OSS Safety Check
        env: 
          RL_COMM_TOK: ${{ secrets.RL_COMMUNITY_TOKEN }}
          RL_PORTAL_TOK: ${{ secrets.RL_PORTAL_TOKEN }}
          RL_PORTAL_SRV: ${{ secrets.RL_PORTAL_SERVER }}
          RL_PORTAL_ORG: ${{ secrets.RL_PORTAL_ORGANIZATION }}
          RL_PORTAL_GRP: ${{ secrets.RL_PORTAL_GROUP }}
        run: |
          # Check version of RL-Protect
          rl-protect --version
          
          # Scan via Portal API
          # rl-protect scan --scan-path=package.json --rl-token="${RL_PORTAL_TOK}" --rl-portal-server="${RL_PORTAL_SRV}" --rl-portal-org="${RL_PORTAL_ORG}" --return-status         
          
          # Scan via free Community API
          rl-protect scan --scan-path=package.json --rl-token="${RL_COMM_TOK}" --return-status


