name: OSS Safety Check with RL-Protect

on:
  workflow_dispatch:

jobs:

  OSS-Check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out 
        uses: actions/checkout@v6
        
      - name: Setup Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: 3.14
          check-latest: true
          pip-install: rl-protect

      - name: OSS Safety Check
        env: 
          RL_COMM_TOK: ${{ secrets.RL_COMMUNITY_TOKEN }}
          RL_PORTAL_TOK: ${{ secrets.RL_PORTAL_TOKEN }}
          RL_PORTAL_SRV: ${{ secrets.RL_PORTAL_SERVER }}
          RL_PORTAL_ORG: ${{ secrets.RL_PORTAL_ORGANIZATION }}
        run: |
          # Check version of RL-Protect
          rl-protect --version
          
          # Scan via Portal API
          rl-protect scan --scan-path=package.json --check-deps=release,transitive --transitive-depth=3 --fail-only --concise --save-report oss-safety-report.json --return-status --rl-token="${RL_PORTAL_TOK}" --rl-portal-server="${RL_PORTAL_SRV}" --rl-portal-org="${RL_PORTAL_ORG}"         
          
          # Scan via free Community API
          # rl-protect scan --scan-path=package.json --check-deps=release,transitive --transitive-depth=3 --fail-only --concise --save-report oss-safety-report.json --return-status --rl-token="${RL_COMM_TOK}"

      - name: Archive Report
        if: success() || failure()
        uses: actions/upload-artifact@v6
        with:
          name: oss-safety-report.json
          path: .

